package com.thinvent.rules.dao.businesslayer;

// Generated Jan 10, 2008 10:00:32 AM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Portletmode generated by hbm2java
 */
public class Portletmode implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private PortletmodePK comp_id;
	private String portletmodename;
	private Portlet portlet;
	private Set<Portletdrool> portletdrools = new HashSet<Portletdrool>(0);

	public Portletmode() {
	}

	public Portletmode(PortletmodePK comp_id) {
		this.comp_id = comp_id;
	}

	public Portletmode(PortletmodePK comp_id, String portletmodename, Portlet portlet, Set<Portletdrool> portletdrools) {
		this.comp_id = comp_id;
		this.portletmodename = portletmodename;
		this.portlet = portlet;
		this.portletdrools = portletdrools;
	}

	public PortletmodePK getComp_id() {
		return this.comp_id;
	}

	public void setComp_id(PortletmodePK comp_id) {
		this.comp_id = comp_id;
	}

	public String getPortletmodename() {
		return this.portletmodename;
	}

	public void setPortletmodename(String portletmodename) {
		this.portletmodename = portletmodename;
	}

	public Portlet getPortlet() {
		return this.portlet;
	}

	public void setPortlet(Portlet portlet) {
		this.portlet = portlet;
	}

	public void setPortletdrools(Set<Portletdrool> portletdrools) {
		this.portletdrools = portletdrools;
	}

	public Set<Portletdrool> getPortletdrools() {
		return portletdrools;
	}



}
