package com.thinvent.rules.dao.businesslayer;

// Generated Jan 10, 2008 10:00:32 AM by Hibernate Tools 3.2.0.CR1

/**
 * PortletdroolPK generated by hbm2java
 */
public class PortletdroolPK implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String country;
	private String portletid;
	private String portletmodeid;
	private Integer sequence;

	public PortletdroolPK() {
	}

	public PortletdroolPK(String country, String portletid, String portletmodeid, Integer sequence) {
		this.country = country;
		this.portletid = portletid;
		this.portletmodeid = portletmodeid;
		this.sequence = sequence;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getPortletid() {
		return this.portletid;
	}

	public void setPortletid(String portletid) {
		this.portletid = portletid;
	}

	public String getPortletmodeid() {
		return portletmodeid;
	}

	public void setPortletmodeid(String portletmodeid) {
		this.portletmodeid = portletmodeid;
	}

	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

}
