package com.thinvent.rules.dao.businesslayer;

// Generated Jan 10, 2008 10:00:32 AM by Hibernate Tools 3.2.0.CR1

/**
 * PortletmodePK generated by hbm2java
 */
public class PortletmodePK implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String portletid;
	private String portletmodeid;

	public PortletmodePK() {
	}

	public PortletmodePK(String portletid, String portletmodeid) {
		this.portletid = portletid;
		this.portletmodeid = portletmodeid;
	}

	public String getPortletid() {
		return this.portletid;
	}

	public void setPortletid(String portletid) {
		this.portletid = portletid;
	}

	public String getPortletmodeid() {
		return portletmodeid;
	}

	public void setPortletmodeid(String portletmodeid) {
		this.portletmodeid = portletmodeid;
	}

}
