INSERT INTO WEBSITE VALUES('欧盟企业总司(企业)','http://ec.europa.eu/enterprise/news/',3,'adress','针对企业','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('欧盟企业总司(消费者)','http://ec.europa.eu/consumers/safety/rapex/alerts/main/index.cfm?event=main.listNotifications&selectedTabIdx=1',3,'adress','针对消费者','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(欧盟 中文)','http://economists-pick-research.hktdc.com/business-news/subindex/sc/%E6%AC%A7%E7%9B%9F%E5%95%86%E6%83%85%E5%BF%AB%E8%AE%AF/1X2ZT68A/1/0.htm',3,'adress','欧盟商情中文快报','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(美国 英文)','http://economists-pick-research.hktdc.com/business-news/subindex/en/Business-Alert-EU/1X2ZT68A/1/0.htm',3,'adress','欧盟商情英文快报','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(美国 中文)','http://economists-pick-research.hktdc.com/business-news/subindex/sc/美国商情快讯/1X300W0C/1/0.htm',3,'adress','美国商情中文快报','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(美国 英文)','http://economists-pick-research.hktdc.com/business-news/subindex/en/Business-Alert-US/1X300W0C/1/0.htm',3,'adress','美国商情英文快报','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国FDA(News)','http://www.fda.gov/NewsEvents/Newsroom/PressAnnouncements/default.htm',3,'adress','新闻发布','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国FDA(Safety)','http://www.fda.gov/Safety/Recalls/',3,'adress','安全警告','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国CPSC新闻间','http://www.cpsc.gov/en/Newsroom/News-Releases/',3,'adress','最新信息','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国CPSC召回信息','http://www.cpsc.gov/en/Recalls/',3,'adress','最近不合格商品召回信息','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('技术壁垒资源网','http://www.tbtmap.cn/portal/default.jsp',3,'adress','要闻','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('厦门WTO工作站','http://www.xmtbt-sps.gov.cn/alert.asp',3,'adress','预警信息>出口预警','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('中国国际电子商务网','http://trade.ec.com.cn/channel/v3-6-hwscCateinfo.shtml',3,'adress','贸易>海外市场','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('食品伙伴网(食品)','http://news.foodmate.net/guoji/',3,'adress','国际食品','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('食品伙伴网(预警)','http://news.foodmate.net/yujing/',3,'adress','国际预警','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('食品伙伴网(数据查询)','http://db.foodmate.net/rasff/',3,'adress','欧盟食品和饲料类快速预警系统','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国农业部食品安全检验局（新闻）','http://www.fsis.usda.gov/wps/portal/fsis/home',3,'adress','新闻','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国农业部食品安全检验局（法规）','http://www.fsis.usda.gov/wps/portal/fsis/home',3,'adress','政策法规','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国农业部食品安全检验局（召回）','http://www.fsis.usda.gov/wps/portal/fsis/home',3,'adress','召回','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国农业部动植物卫生检验局（APHIS）','http://www.aphis.usda.gov/wps/portal/aphis/newsroom/news?1dmy&urile=wcm%3apath%3a%2Faphis_content_library%2Fsa_newsroom%2Fsa_news%2Fct_aphis_newsroom',3,'adress','Home>Newsroom>News','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('中国质量新闻网','http://www.cqn.com.cn/news/zggmsb/',3,'adress','中国国门时报','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('天祥INTERTEK','http://www.intertek.com.cn/standard.html',3,'adress','法规标准','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('加拿大食品检验局','http://www.inspection.gc.ca/what-s-new/eng/1325713745155/1325713796031',3,'adress','What’s New','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('英国食品标准局','http://www.food.gov.uk/news-updates/news/',3,'adress','News Centre','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('欧洲食品安全委员会','http://www.efsa.europa.eu/en/news/press.htm',3,'adress','Home>News & events>News','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('杭州瑞旭产品技术有限公司(欧洲法规)','http://www.cirs-group.com/reg/news/news_2_17_1.html',3,'adress','法规入口>欧洲REACH法规','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('杭州瑞旭产品技术有限公司(全球法规)','http://www.cirs-group.com/reg/news/news_2_81_1.html',3,'adress','法规入口>全球GHS/CLP法规','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('杭州瑞旭产品技术有限公司(化妆品登记)','http://www.cirs-group.com/reg/news/news_2_102_1.html',3,'adress','法规入口>进出口化妆品登记','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('杭州瑞旭产品技术有限公司(其他法规）','http://www.cirs-group.com/reg/news/news_2_103_1.html',3,'adress','法规入口>其他法规','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('安规与电磁兼容网(行业动态)','http://www.safetyemc.cn/news/news1/',3,'adress','首页>新闻>行业动态','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('安规与电磁兼容网(标准信息)','http://www.safetyemc.cn/news/news3/',3,'adress','新闻-标准信息','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('安规与电磁兼容网(能效环保)','http://www.safetyemc.cn/news/news6/',3,'adress','新闻-能效环保','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('foodnavigator(转基因)','http://www.foodnavigator.com/On-your-radar/GM-food',3,'adress','Topics>GM food','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('foodnavigator(自然)','http://www.foodnavigator.com/On-your-radar/Natural-and-clean-label',3,'adress','Topics > Natural and clean label','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('欧洲化学品管理局（ECHA)','http://echa.europa.eu/news-and-events/news-alerts',3,'adress','News and Events','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国农业部','http://www.usda.gov/wps/portal/usda/usdahome?navid=LATEST_RELEASES&parentnav=NEWSROOM&navtype=RT&edeployment_action=latestreleases',3,'adress',' Newsroom / Latest Releases','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('化学观察网','http://chemicalwatch.com/news/?q=&offset=0',3,'adress','News>>All News','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('中国技术性贸易措施网','http://www.tbt-sps.gov.cn/riskinfo/riskinfo/Pages/default.aspx',3,'adress','风险预警 > 预警公告 ','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('中国贸易救济信息网','http://www.cacs.gov.cn/cacs/newcs/list.aspx?navid=A17&id=184',3,'adress',' 法律与研究 > 动态','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳新食品标准局','http://www.foodstandards.gov.au/media/pages/mediareleases/Default.aspx',3,'adress','Media Centre> Media Releases','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('德国联邦环保局','http://www.umweltbundesamt.de/en/press/pressinformation',3,'adress','Press> releases','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('韩国技术与标准厅','http://www.kats.go.kr/en_kats/news/KAEU04_1_1.asp',3,'adress','News&Publications','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('IPPC','https://www.ippc.int/news',3,'adress',' Latest News','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('CAC','http://www.codexalimentarius.org/roster/news-archive/en/',3,'adress','lastest news>news archive','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚农药兽药管理局','http://www.apvma.gov.au/news_media/news/index.php',3,'adress','News Print Increase Decrease','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('新西兰食品安全局','http://www.foodsafety.govt.nz/news/',3,'adress','News','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国农业部营销署','http://www.ams.usda.gov/AMSv1.0/ams.fetchTemplateData.do?template=TemplateU&navID=Newsroom&topNav=Newsroom&page=Newsroom&acct=AMSPW',3,'adress','Newsroom','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('ISO','http://www.iso.org/iso/home/news_index.htm',3,'adress','NEWS','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('欧盟食品饮料行业联盟','http://www.fooddrinkeurope.eu/news/press-releases/',3,'adress','News>Press Releases','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('foodproductiondaily(安全法规)','http://www.foodproductiondaily.com/Safety-Regulation',3,'adress','World > News > Safety & Regulation','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('foodproductiondaily(包装)','http://www.foodproductiondaily.com/Packaging',3,'adress','World > News > Packing','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('农产品加工国际标准跟踪信息网（法规）','http://www.isapp.gov.cn/fgcxdt/index.shtml',3,'adress','法规最新动态','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('农产品加工国际标准跟踪信息网（标准）','http://www.isapp.gov.cn/bzcxdt/index.shtml',3,'adress',' 标准最新动态','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('中国农业外经外贸信息网(贸易政策)','http://www.cafte.gov.cn/maoyizhengce/maoyihuoban/index.shtml',3,'adress','贸易伙伴农业贸易政策','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('中国农业外经外贸信息网(谈判与救济)','http://www.cafte.gov.cn/WTO_succour/index.shtml',3,'adress','农业贸易谈判与救济','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('中国农业外经外贸信息网(技术与质量)','http://www.cafte.gov.cn/jishubiaozhun/index.shtml',3,'adress','农业技术及质量标准','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('加拿大卫生部','http://www.healthycanadians.gc.ca/recall-alert-rappel-avis/search-recherche/result-resultat/en?search_text_1=',3,'adress','Recalls & Alerts','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('WTO检验检疫信息网(最新动态)','http://www.wtociq.gov.cn/zxdt/',3,'adress','最新动态','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('WTO检验检疫信息网(红色预警)','http://www.wtociq.gov.cn/ckyj/hsyj/',3,'adress','出口预警——红色预警','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('WTO检验检疫信息网(橙色预警)','http://www.wtociq.gov.cn/ckyj/csyj/',3,'adress','出口预警——橙色预警','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('WTO检验检疫信息网(黄色预警)','http://www.wtociq.gov.cn/ckyj/husyj/',3,'adress','出口预警——黄色预警','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('WTO检验检疫信息网(焦点关注)','http://www.wtociq.gov.cn/jdgz/',3,'adress','焦点关注','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('国际电工委员会','http://www.iec.ch/newslog/2014/',3,'adress','News & views —— News LOGs——2014','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚食品新闻网','http://www.ausfoodnews.com.au/news',3,'adress','LACAL NEWS','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚农业科学技术部','http://www.aginstitute.com.au/news.html',3,'adress','News/Events> Latest News','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚新西兰食品标准局','http://www.foodstandards.gov.au/media/pages/mediareleases/Default.aspx',3,'adress','Media Centre> Media Releases','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚农业部','http://www.daff.gov.au/about/media-centre/dept-releases',3,'adress',' Media Centre > Latest media releases','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚产品安全召回网(面包)','http://www.recalls.gov.au/content/index.phtml/itemId/952829',3,'adress','Food & groceries > Bakery','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚产品安全召回网(冷冻)','http://www.recalls.gov.au/content/index.phtml/itemId/952824',3,'adress','Food & groceries > Chilled & frozen','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚产品安全召回网(甜食)','http://www.recalls.gov.au/content/index.phtml/itemId/952878',3,'adress','Food & groceries > Confectionery','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚产品安全召回网(乳制品)','http://www.recalls.gov.au/content/index.phtml/itemId/952826',3,'adress','Food & groceries > Dairy & eggs','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚产品安全召回网(饮料)','http://www.recalls.gov.au/content/index.phtml/itemId/952828',3,'adress','Food & groceries > Drinks','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚产品安全召回网(蔬果)','http://www.recalls.gov.au/content/index.phtml/itemId/952827',3,'adress','Food & groceries > Fruit & veg','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚产品安全召回网(食品杂货)','http://www.recalls.gov.au/content/index.phtml/itemId/952830',3,'adress','Food & groceries > Groceries','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('澳大利亚产品安全召回网(肉类)','http://www.recalls.gov.au/content/index.phtml/itemId/952825',3,'adress','Food & groceries > Meat, seafood & deli','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('欧盟企业总司','http://ec.europa.eu/consumers/safety/rapex/alerts/main/index.cfm?event=main.rss',3,'adress','European Commission>Consumers>Safety>Rapex','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('英国新鲜果蔬商业网食品安全与认证','http://www.fruitnet.com/fpj/topic/food-safety-certification',3,'adress','EUROFRUIT>Topics>Food safety & Certification','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国欧盟合作网','http://useu.usmission.gov/agriculture_biotechnology.html',3,'adress','Economic Issues>Agriculture and Biotechnology','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('世界卫生组织','http://www.who.int/csr/don/zh/',3,'adress','疾病爆发新闻','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港卫生署','http://www.dh.gov.hk/scindex.html',3,'adress','简体中文版>最新消息','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国疾病预防控制中心CDC','http://wwwnc.cdc.gov/travel/notices',3,'adress','TravelersHealth>Travel Notices','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('中国检验检疫科学研究院','http://www.caiq.org.cn/xkdt/wsjy/index.shtml',3,'adress','科学动态>卫生检疫','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港卫生防护中心','http://sc.chp.gov.hk/TuniS/www.chp.gov.hk/tc/whatsnew.html',3,'adress','简体中文版-最新资讯','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('英国政府PublicHealthEngland公告（英国卫生防护局）','https://www.gov.uk/government/announcements?departments%5B%5D=public-health-england',3,'adress','Announcement>PublicHealthEngland','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('质检总局(疫情公告)','http://www.aqsiq.gov.cn/ztlm/2013/lxjk/',3,'adress','国际旅行健康与疫情信息专栏>疫情公告','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('质检总局(疫情预警)','http://www.aqsiq.gov.cn/xxgk_13386/tsxx/yqts/xxgkml_1_4443.htm',3,'adress','提示信息>疫情预警','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('环球网','http://health.huanqiu.com/health_news/',3,'adress','健康热点','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('质检总局(新闻)','http://www.aqsiq/xwpd/ftpxw/',3,'adress','新闻频道>非图片新闻','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('质检总局(警示通报)','http://www.aqsiq/bmwl/dzwjyjgs/jstb/index.htm',3,'adress','动植物检疫监管司警示通报','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('厦门WTO工作站','http://www.xmtbt-sps.gov.cn/alertInport.asp',3,'adress','进口预警','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国农业部动植物卫生检验局（APHIS）','http://www.aphis.usda.gov/wps/portal/aphis/ourfocus/animalhealth?1dmy&urile=wcm%3apath%3a%2Faphis_content_library%2Fsa_our_focus%2Fsa_animal_health%2Fsa_import_into_us%2Fct_animal_disease_status',3,'adress','U.S>Country Animal Disease Status','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('加拿大产品标准局','http://www.scc.ca/news-events/news',3,'adress','News & Events','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('加拿大官网','http://news.gc.ca/web/nwsprdct-en.do?mthd=tp&crtr.tp1D=1',3,'adress','News releases','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国商务部国际贸易管理局','http://otexa.ita.doc.gov/',3,'adress','Announcements','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('美国联邦委员会','http://www.ftc.gov/news-events',3,'adress','News and Events','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(婴童 市场)','http://product-industries-research.hktdc.com/business-news/subindex/sc/婴童用品/1X3X8VKV/1/0.htm',3,'adress','婴童用品>市场趋势','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(婴童 安全)','http://product-industries-research.hktdc.com/business-news/subindex/sc/婴童用品/1X3X8VLU/1/0.htm',3,'adress','婴童用品>产品安全条例及标准','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(鞋履 市场)','http://product-industries-research.hktdc.com/business-news/subindex/sc/鞋履及皮革用品/1X3X15ST/1/0.htm',3,'adress','鞋履及皮革用品>市场趋势','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(鞋履 安全)','http://product-industries-research.hktdc.com/business-news/subindex/sc/鞋履及皮革用品/1X3X15UR/1/0.htm',3,'adress','鞋履及皮革用品>产品安全条例及标准','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(玩具 市场)','http://product-industries-research.hktdc.com/business-news/subindex/sc/玩具及运动用品/1X3WE0GK/1/0.htm',3,'adress','玩具及运动产品>市场趋势','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(玩具 安全)','http://product-industries-research.hktdc.com/business-news/subindex/sc/玩具及运动用品/1X3WE0II/1/0.htm',3,'adress','玩具及运动产品>产品安全条例及标准','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(钟表 市场)','http://product-industries-research.hktdc.com/business-news/subindex/sc/钟表-珠宝及眼镜/1X3W6AOI/1/0.htm',3,'adress','钟表珠宝及眼睛>市场趋势','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(钟表 安全)','http://product-industries-research.hktdc.com/business-news/subindex/sc/钟表-珠宝及眼镜/1X3W6AQG/1/0.htm',3,'adress','钟表珠宝及眼睛>产品安全条例及标准','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(电子 市场)','http://product-industries-research.hktdc.com/business-news/subindex/sc/%E7%94%B5%E5%AD%90%E5%8F%8A%E7%94%B5%E5%99%A8%E4%BA%A7%E5%93%81/1X3VBFK7/1/0.htm',3,'adress','电子及电器产品>市场趋势','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(电子 安全)','http://product-industries-research.hktdc.com/business-news/subindex/sc/电子及电器产品/1X3VBFM5/1/0.htm',3,'adress','电子及电器产品>产品安全条例及标准','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(服装 市场)','http://product-industries-research.hktdc.com/business-news/subindex/sc/服装及纺织品/1X3VJ5C9/1/0.htm',3,'adress','服装及纺织品>市场趋势','','2015-8-31','0')
INSERT INTO WEBSITE VALUES('香港贸发网(服装 安全)','http://product-industries-research.hktdc.com/business-news/subindex/sc/服装及纺织品/1X3VJ5E7/1/0.htm',3,'adress','服装及纺织品>产品安全条例及标准','','2015-8-31','0')